import gzip
from pathlib import Path

Import("env")

PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))
WEB_APP_PATH = PROJECT_DIR.parent / "index.html"
OUTPUT_PATH = PROJECT_DIR / "src" / "generated_web_app.h"


def format_bytes(data):
    lines = []

    for index in range(0, len(data), 12):
        chunk = data[index:index + 12]
        lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk))

    return ",\n".join(lines)


def build_web_asset(source, output):
    html = source.read_bytes()
    compressed = gzip.compress(html, compresslevel=9, mtime=0)
    output.write_text(
        "// Generated by scripts/build_web_asset.py. Do not edit by hand.\n"
        "// Canonical source: ../../index.html\n"
        "#pragma once\n\n"
        "#include <Arduino.h>\n\n"
        f"const unsigned int WEB_APP_GZ_LEN = {len(compressed)};\n"
        "const unsigned char WEB_APP_GZ[] PROGMEM = {\n"
        f"{format_bytes(compressed)}\n"
        "};\n",
        encoding="utf-8"
    )


if not WEB_APP_PATH.exists():
    raise FileNotFoundError(f"Web app source not found: {WEB_APP_PATH}")

build_web_asset(WEB_APP_PATH, OUTPUT_PATH)
